name: todo-app
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
  frontend:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    command: "npm run start"
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    expose:
      - "3000"
    ports:
      - "3000:3000"

  backend:
    image: todo-app/backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "3001"
    ports:
      - "8001:3001"
    command: "python src/server.py"
    environment:
      - DEBUG=true
    env_file:
      - path: ./.env
        required: true

    